project:
  type: website
  output-dir: docs

website:
  title: "CEFI Ecological Forecasting Challenges"
  description: "A site to bring together Canadian researchers interested in ecological forecasting challenges"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Links.qmd
  page-footer:
    left:
      - text: "This site is currently maintained by Dr. Eliot McIntire, with contributions by Josie Hughes. Powered by Quarto"
  comments:
      hypothesis:
        theme: clean
        openSidebar: false
  
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-E87KD90Z2J"
    anonymize-ip: true
  open-graph: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    smooth-scroll: true
    link-external-newwindow: true
    toc: true


